language: node_js
node_js:
  - "8.9.4"

branches:
  only:
  - master
  - develop
  
before_script:
  - yarn global add ionic cordova

script:
  - ionic config set -g yarn true
  - ionic cordova build browser --prod

deploy:
  edge:
    branch: v1.8.47
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: www